"""Renders synthetic Rubik's cube frames with exact face-corner labels.

The detector has to answer one question: where are the four corners of the face currently pointing
at the camera. That label is impossible to annotate accurately by hand and free to compute here, so
training data is generated by projecting a cube model rather than by labelling photographs.

Domain randomisation covers what broke the geometric detector on real frames: perspective tilt,
fingers over stickers, specular highlights, warm indoor light, and cluttered desks.
"""

import argparse
import math
import os
import glob
import numpy as np
import cv2

# Sticker palettes. Real cubes vary a lot, and the greens in the recorded video were closer to lime
# than to the textbook green, so each palette is also jittered per render.
_PALETTES_RGB = [
    # white, red, green, yellow, orange, blue
    [(244, 243, 238), (216, 65, 47), (111, 191, 62), (240, 206, 29), (232, 132, 42), (45, 111, 208)],
    [(238, 238, 232), (200, 45, 40), (80, 170, 85), (250, 220, 40), (245, 150, 35), (30, 90, 190)],
    [(250, 248, 240), (230, 60, 60), (130, 200, 70), (245, 230, 60), (255, 145, 20), (40, 120, 220)],
]
# Everything downstream draws with OpenCV, which takes BGR.
PALETTES = [[tuple(reversed(c)) for c in palette] for palette in _PALETTES_RGB]

# How much bigger the front face must project than the runner-up before the frame counts as
# showing a definite face. Below this the two are interchangeable and the label is a coin toss.
# Kept only just above 1: a ratio of 1.35 corresponds to a 36 degree tilt, so it was discarding
# most three-quarter views, which are exactly the poses the app needs to survive.
MIN_FACE_DOMINANCE = 1.10

FACE_AXES = [
    # (normal, right, up) in cube space; one entry per face
    ((0, 0, 1), (1, 0, 0), (0, 1, 0)),
    ((0, 0, -1), (-1, 0, 0), (0, 1, 0)),
    ((1, 0, 0), (0, 0, -1), (0, 1, 0)),
    ((-1, 0, 0), (0, 0, 1), (0, 1, 0)),
    ((0, 1, 0), (1, 0, 0), (0, 0, -1)),
    ((0, -1, 0), (1, 0, 0), (0, 0, 1)),
]


def rotation_matrix(yaw, pitch, roll):
    cy, sy = math.cos(yaw), math.sin(yaw)
    cp, sp = math.cos(pitch), math.sin(pitch)
    cr, sr = math.cos(roll), math.sin(roll)
    ry = np.array([[cy, 0, sy], [0, 1, 0], [-sy, 0, cy]])
    rx = np.array([[1, 0, 0], [0, cp, -sp], [0, sp, cp]])
    rz = np.array([[cr, -sr, 0], [sr, cr, 0], [0, 0, 1]])
    return rz @ rx @ ry


def rounded_square(half, radius, steps=5):
    """Sticker outline in face-local 2D, as a closed polygon with rounded corners."""
    pts = []
    inner = half - radius
    for cx, cy, start in ((inner, inner, 0), (-inner, inner, 90),
                          (-inner, -inner, 180), (inner, -inner, 270)):
        for i in range(steps + 1):
            angle = math.radians(start + 90 * i / steps)
            pts.append((cx + radius * math.cos(angle), cy + radius * math.sin(angle)))
    return np.array(pts, dtype=np.float32)


class CubeRenderer:
    """Renders at the camera's own aspect ratio. Training on squares and deploying on a portrait
    frame put the model out of distribution, so the canvas shape is a parameter."""

    def __init__(self, size=256, rng=None, height=None):
        self.size = size                      # canvas width
        self.height = height or size
        self.rng = rng or np.random.default_rng()

    def project(self, points3d, rot, translation, focal):
        cam = points3d @ rot.T + translation
        z = np.clip(cam[:, 2], 1e-3, None)
        x = focal * cam[:, 0] / z + self.size / 2
        y = -focal * cam[:, 1] / z + self.height / 2
        return np.stack([x, y], axis=1), cam

    def render(self):
        rng = self.rng
        size = self.size
        canvas = self.background()

        palette = [np.array(c, dtype=np.float32) for c in PALETTES[rng.integers(len(PALETTES))]]
        palette = [np.clip(c + rng.normal(0, 9, 3), 0, 255) for c in palette]

        # Pose. Yaw/pitch stay wide so three-quarter views, which the lattice fit could not handle,
        # are well represented rather than treated as rare.
        yaw = rng.uniform(-1.05, 1.05)
        pitch = rng.uniform(-0.95, 0.95)
        roll = rng.uniform(-math.pi, math.pi)
        rot = rotation_matrix(yaw, pitch, roll)
        focal = rng.uniform(0.85, 3.3) * size      # wide and narrow fields of view
        distance = rng.uniform(3.5, 13.0)          # cube filling the frame, and far away
        aspect = self.height / self.size
        offset = np.array([rng.uniform(-1.1, 1.1),
                           rng.uniform(-1.1, 1.1) * aspect, distance])

        light = np.array([rng.uniform(-1, 1), rng.uniform(0.2, 1), rng.uniform(0.3, 1)])
        light /= np.linalg.norm(light)
        warmth = rng.uniform(-0.16, 0.22)   # indoor lighting runs warm

        faces = []
        for index, (normal, right, up) in enumerate(FACE_AXES):
            n = np.array(normal, dtype=np.float32)
            cam_normal = rot @ n
            center_cam = rot @ n + offset
            if float(np.dot(cam_normal, center_cam)) >= 0:
                continue  # facing away
            corners3d = np.array([
                n + np.array(right) + np.array(up), n - np.array(right) + np.array(up),
                n - np.array(right) - np.array(up), n + np.array(right) - np.array(up)],
                dtype=np.float32)
            projected, _ = self.project(corners3d, rot, offset, focal)
            area = abs(cv2.contourArea(projected.astype(np.float32)))
            faces.append((area, index, n, np.array(right), np.array(up), projected, cam_normal))

        if not faces:
            return None
        faces.sort(key=lambda f: f[0])  # painter's algorithm: smallest (most oblique) first

        body = np.array([18, 18, 20], dtype=np.float32) + rng.normal(0, 6, 3)
        for area, index, n, right, up, projected, cam_normal in faces:
            cv2.fillConvexPoly(canvas, projected.astype(np.int32),
                               tuple(np.clip(body, 0, 255).tolist()))
            shade = 0.66 + 0.34 * max(0.0, float(np.dot(cam_normal, light)))
            gap = rng.uniform(0.09, 0.22)
            half = (1.0 - gap) / 3.0
            outline = rounded_square(half, half * rng.uniform(0.18, 0.34))
            for row in range(3):
                for col in range(3):
                    cu = (col - 1) * 2.0 / 3.0
                    cv_ = (1 - row) * 2.0 / 3.0
                    local = np.array([[cu + p[0], cv_ + p[1]] for p in outline], dtype=np.float32)
                    pts3d = np.array([n + right * u + up * v for u, v in local], dtype=np.float32)
                    pts2d, _ = self.project(pts3d, rot, offset, focal)
                    color = palette[rng.integers(6)] * shade
                    color = self.apply_warmth(color, warmth)
                    cv2.fillPoly(canvas, [pts2d.astype(np.int32)],
                                 tuple(np.clip(color, 0, 255).tolist()), lineType=cv2.LINE_AA)

        # The label is the face most squarely facing the camera, i.e. the largest projected one.
        ranked = sorted(faces, key=lambda f: -f[0])
        target = ranked[0]
        corners = order_corners(target[5])

        # Near 45 degrees two faces project to almost the same area and "the largest" flips between
        # them, so visually identical frames would carry corners from different faces. Those poses
        # are labelled absent instead: the app wants a face squarely presented, not a coin toss.
        dominant = len(ranked) == 1 or ranked[0][0] >= ranked[1][0] * MIN_FACE_DOMINANCE

        canvas = self.add_specular(canvas, faces, rng)
        canvas = self.occlude(canvas, corners, rng)
        canvas = self.photometric(canvas, warmth, rng)

        visible = self.visibility(corners) if dominant else 0.0
        return canvas, corners, visible

    def apply_warmth(self, bgr, warmth):
        return np.array([bgr[0] * (1 - warmth), bgr[1], bgr[2] * (1 + warmth * 0.8)])

    def background(self):
        rng = self.rng
        size = self.size
        if BACKGROUNDS and rng.random() < BACKGROUND_SHARE:
            src = _background_image(BACKGROUNDS[rng.integers(len(BACKGROUNDS))])
            if src is not None and src.shape[0] > 8 and src.shape[1] > 8:
                # A random window of a real scene, so 100 frames yield far more than 100 contexts.
                zoom = rng.uniform(0.45, 1.0)
                h, w = src.shape[:2]
                ch = max(8, int(h * zoom))
                cw = max(8, min(w, int(ch * size / self.height)))
                y = int(rng.integers(0, h - ch + 1))
                x = int(rng.integers(0, w - cw + 1))
                src = src[y:y + ch, x:x + cw]
                if rng.random() < 0.5:
                    src = src[:, ::-1]
                src = cv2.resize(np.ascontiguousarray(src), (size, self.height)).astype(np.float32)
                src = src * rng.uniform(0.8, 1.2, 3) + rng.uniform(-15, 15)
                return cv2.GaussianBlur(np.clip(src, 0, 255), (0, 0), rng.uniform(0.3, 2.0))
        base = rng.uniform(30, 210, 3)
        canvas = np.ones((self.height, size, 3), np.float32) * base
        for _ in range(int(rng.integers(2, 9))):
            color = rng.uniform(0, 255, 3)
            pt1 = rng.integers(-size // 2, size, 2)
            pt2 = rng.integers(0, size + size // 2, 2)
            cv2.rectangle(canvas, tuple(pt1.tolist()), tuple(pt2.tolist()),
                          tuple(color.tolist()), -1)
        return cv2.GaussianBlur(canvas, (0, 0), rng.uniform(1.0, 6.0))

    def add_specular(self, canvas, faces, rng):
        """Glare blobs. These are what pushed sticker patches out of their colour band on real frames."""
        for _ in range(int(rng.integers(0, 3))):
            area, index, n, right, up, projected, cam_normal = faces[rng.integers(len(faces))]
            centre = projected.mean(axis=0)
            axes = (int(rng.uniform(4, 26)), int(rng.uniform(4, 26)))
            layer = np.zeros_like(canvas)
            cv2.ellipse(layer, (int(centre[0] + rng.uniform(-30, 30)),
                                int(centre[1] + rng.uniform(-30, 30))),
                        axes, rng.uniform(0, 180), 0, 360, (255, 255, 255), -1)
            layer = cv2.GaussianBlur(layer, (0, 0), rng.uniform(4, 14))
            canvas = np.clip(canvas + layer * rng.uniform(0.25, 0.85), 0, 255)
        return canvas

    def occlude(self, canvas, corners, rng):
        """
        A hand holding the cube: a palm mass with fingers reaching across an edge.

        Real occlusions come in from one side and cast shadow onto the stickers they touch, which
        is what makes an occluded patch read as a plausible flat colour. Scattered ellipses did not
        reproduce that, and fingers over the cube were the most common real failure.
        """
        if rng.random() < 0.18:
            return canvas
        skin = np.array([rng.uniform(115, 180), rng.uniform(145, 200), rng.uniform(180, 235)])
        layer = np.zeros_like(canvas)
        mask = np.zeros(canvas.shape[:2], np.float32)

        centre = corners.mean(axis=0)
        side = rng.integers(4)
        anchor = (corners[side] + corners[(side + 1) % 4]) / 2.0
        outward = anchor - centre
        norm = np.linalg.norm(outward) + 1e-6
        outward = outward / norm

        # Palm sits outside the face, fingers reach back across it.
        palm = anchor + outward * rng.uniform(40, 90)
        cv2.ellipse(layer, (int(palm[0]), int(palm[1])),
                    (int(rng.uniform(45, 95)), int(rng.uniform(35, 80))),
                    rng.uniform(0, 180), 0, 360, tuple(skin.tolist()), -1)
        cv2.ellipse(mask, (int(palm[0]), int(palm[1])),
                    (int(rng.uniform(45, 95)), int(rng.uniform(35, 80))),
                    rng.uniform(0, 180), 0, 360, 1.0, -1)

        perpendicular = np.array([-outward[1], outward[0]])
        for finger in range(int(rng.integers(1, 4))):
            offset = rng.uniform(-1.0, 1.0) * norm * 0.7
            reach = rng.uniform(0.15, 0.75) * norm
            tip = anchor + perpendicular * offset - outward * reach
            root = anchor + perpendicular * offset + outward * rng.uniform(10, 40)
            width = int(rng.uniform(9, 26))
            cv2.line(layer, (int(root[0]), int(root[1])), (int(tip[0]), int(tip[1])),
                     tuple((skin * rng.uniform(0.9, 1.06)).tolist()), width)
            cv2.line(mask, (int(root[0]), int(root[1])), (int(tip[0]), int(tip[1])), 1.0, width)

        mask = cv2.GaussianBlur(mask, (0, 0), rng.uniform(1.2, 3.5))
        canvas = canvas * (1 - mask[..., None]) + layer * mask[..., None]

        # Contact shadow just beyond the fingers, which darkens neighbouring stickers.
        shadow = cv2.GaussianBlur(mask, (0, 0), rng.uniform(6, 16)) * rng.uniform(0.15, 0.45)
        shadow = np.clip(shadow - mask, 0, 1)
        return canvas * (1 - shadow[..., None])

    def photometric(self, canvas, warmth, rng):
        canvas = canvas * rng.uniform(0.72, 1.25) + rng.uniform(-18, 18)
        if rng.random() < 0.5:
            gradient = np.linspace(rng.uniform(0.75, 1.0), rng.uniform(0.75, 1.0), self.size)
            canvas = canvas * gradient[None, :, None]
        else:
            gradient = np.linspace(rng.uniform(0.75, 1.0), rng.uniform(0.75, 1.0), self.height)
            canvas = canvas * gradient[:, None, None]
        if rng.random() < 0.35:                       # motion blur from a moving hand
            k = int(rng.integers(3, 10))
            kernel = np.zeros((k, k), np.float32)
            kernel[k // 2, :] = 1.0 / k
            kernel = cv2.warpAffine(kernel, cv2.getRotationMatrix2D((k / 2, k / 2),
                                                                    rng.uniform(0, 180), 1), (k, k))
            canvas = cv2.filter2D(canvas, -1, kernel / max(kernel.sum(), 1e-6))
        canvas = canvas + rng.normal(0, rng.uniform(1, 11), canvas.shape)
        canvas = np.clip(canvas, 0, 255).astype(np.uint8)
        if rng.random() < 0.4:
            quality = int(rng.integers(35, 92))
            ok, buf = cv2.imencode('.jpg', canvas, [cv2.IMWRITE_JPEG_QUALITY, quality])
            if ok:
                canvas = cv2.imdecode(buf, cv2.IMREAD_COLOR)
        return canvas

    def visibility(self, corners):
        """
        1 when enough of the labelled face is in frame to be worth reading.

        Judged on the share of the face actually inside the frame rather than on a corner count.
        A cube held close enough to overflow the frame still shows a perfectly readable face, and
        requiring three corners in view was rejecting exactly those close-up shots.
        """
        area = abs(cv2.contourArea(corners.astype(np.float32)))
        if area <= 0:
            return 0.0
        clipped = corners.copy()
        clipped[:, 0] = np.clip(clipped[:, 0], 0, self.size)
        clipped[:, 1] = np.clip(clipped[:, 1], 0, self.height)
        visible = abs(cv2.contourArea(clipped.astype(np.float32)))
        min_area = (self.size * self.height) * 0.010
        return 1.0 if visible > min_area and visible / area > 0.55 else 0.0


def order_corners(pts):
    """Clockwise from the top-left-most corner, matching the app's own corner convention."""
    centre = pts.mean(axis=0)
    angles = np.arctan2(pts[:, 1] - centre[1], pts[:, 0] - centre[0])
    ordered = pts[np.argsort(angles)]
    start = int(np.argmin(ordered[:, 0] + ordered[:, 1]))
    return np.array([ordered[(start + i) % 4] for i in range(4)], dtype=np.float32)


BACKGROUNDS = []
# Share of renders drawn over a real background when any were supplied.
BACKGROUND_SHARE = 0.75
_BACKGROUND_CACHE = {}


def _background_image(path):
    image = _BACKGROUND_CACHE.get(path)
    if image is None:
        image = cv2.imread(path)
        if image is not None and len(_BACKGROUND_CACHE) < 512:
            _BACKGROUND_CACHE[path] = image
    return image


def load_backgrounds(paths):
    global BACKGROUNDS
    BACKGROUNDS = []
    for pattern in paths:
        BACKGROUNDS.extend(sorted(glob.glob(pattern)))
    return BACKGROUNDS


def render_shard(task):
    """Renders one contiguous slice into the shared memmap. Runs in a worker process."""
    start, count, size, height, seed, out, backgrounds, preview = task
    if backgrounds:
        load_backgrounds(backgrounds)
    rng = np.random.default_rng(seed)
    renderer = CubeRenderer(size, rng, height)
    images = np.lib.format.open_memmap(os.path.join(out, 'images.npy'), mode='r+')
    labels = np.lib.format.open_memmap(os.path.join(out, 'corners.npy'), mode='r+')
    present = np.lib.format.open_memmap(os.path.join(out, 'present.npy'), mode='r+')

    written = 0
    while written < count:
        index = start + written
        if rng.random() < 0.10:
            images[index] = renderer.photometric(renderer.background(), 0.0, rng)
            labels[index] = 0.0
            present[index] = 0.0
            written += 1
            continue
        result = renderer.render()
        if result is None:
            continue
        canvas, corners, visible = result
        images[index] = canvas
        labels[index] = (corners / np.array([size, height], dtype=np.float32)).reshape(-1)
        present[index] = visible
        if written < preview:
            annotated = canvas.copy()
            cv2.polylines(annotated, [corners.astype(np.int32)], True, (0, 255, 255), 2)
            cv2.imwrite(os.path.join(out, f'preview_{index:04d}.png'), annotated)
        written += 1
        # Flush regularly. Several workers writing into one large memmap otherwise pile up
        # gigabytes of dirty pages between them, and the run dies to the OOM killer near the end.
        if written % 512 == 0:
            images.flush()
    images.flush(); labels.flush(); present.flush()
    return count


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--count', type=int, default=40000)
    parser.add_argument('--size', type=int, default=256, help='canvas width')
    parser.add_argument('--height', type=int, default=0, help='canvas height, defaults to square')
    parser.add_argument('--out', default='data/synth')
    parser.add_argument('--seed', type=int, default=0)
    parser.add_argument('--backgrounds', nargs='*', default=[])
    parser.add_argument('--preview', type=int, default=0, help='write N annotated preview images')
    parser.add_argument('--workers', type=int, default=0, help='0 renders in this process')
    args = parser.parse_args()

    if args.backgrounds:
        found = load_backgrounds(args.backgrounds)
        print(f'using {len(found)} background images')

    os.makedirs(args.out, exist_ok=True)
    height = args.height or args.size

    if args.workers > 0:
        import multiprocessing as mp
        for name, shape, dtype in (('images.npy', (args.count, height, args.size, 3), np.uint8),
                                   ('corners.npy', (args.count, 8), np.float32),
                                   ('present.npy', (args.count, 1), np.float32)):
            np.lib.format.open_memmap(os.path.join(args.out, name), mode='w+',
                                      dtype=dtype, shape=shape)
        per = (args.count + args.workers - 1) // args.workers
        tasks = []
        for worker in range(args.workers):
            start = worker * per
            count = min(per, args.count - start)
            if count <= 0:
                break
            tasks.append((start, count, args.size, height, args.seed + 1000 * worker + 1, args.out,
                          args.backgrounds, args.preview if worker == 0 else 0))
        with mp.Pool(len(tasks)) as pool:
            done = 0
            for finished in pool.imap_unordered(render_shard, tasks):
                done += finished
                print(f'{done}/{args.count}', flush=True)
        present = np.load(os.path.join(args.out, 'present.npy'), mmap_mode='r')
        print(f'wrote {args.out}  present={float(np.asarray(present).mean()):.3f}')
        return

    rng = np.random.default_rng(args.seed)
    renderer = CubeRenderer(args.size, rng)

    images = np.zeros((args.count, args.size, args.size, 3), np.uint8)
    labels = np.zeros((args.count, 8), np.float32)
    present = np.zeros((args.count, 1), np.float32)

    written = 0
    while written < args.count:
        # A share of pure-background frames, so the model learns to say "no cube" instead of
        # always regressing a quadrilateral onto whatever happens to be in view.
        if rng.random() < 0.10:
            empty = renderer.photometric(renderer.background(), 0.0, rng)
            images[written] = empty
            labels[written] = 0.0
            present[written] = 0.0
            written += 1
            continue
        result = renderer.render()
        if result is None:
            continue
        canvas, corners, visible = result
        images[written] = canvas
        labels[written] = (corners / args.size).reshape(-1)
        present[written] = visible
        if written < args.preview:
            preview = canvas.copy()
            cv2.polylines(preview, [corners.astype(np.int32)], True, (0, 255, 255), 2)
            for i, (x, y) in enumerate(corners):
                cv2.circle(preview, (int(x), int(y)), 4, (0, 0, 255), -1)
                cv2.putText(preview, str(i), (int(x) + 5, int(y)),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.4, (255, 255, 255), 1)
            cv2.imwrite(os.path.join(args.out, f'preview_{written:03d}.png'), preview)
        written += 1
        if written % 5000 == 0:
            print(f'{written}/{args.count}')

    path = os.path.join(args.out, 'dataset.npz')
    np.savez_compressed(path, images=images, corners=labels, present=present)
    print(f'wrote {path}  present={present.mean():.3f}')


if __name__ == '__main__':
    main()
